Added routes for app
htmlacademy-react/30818-what-to-watch-9 pull request #4
Opened 2022-02-16 19:39 UTC by olegsorokin

2022-02-17 21:34 UTC, dianatsevan requested changes

2022-02-17 21:34 UTC, dianatsevan commented on project/src/components/private-route/private-route.tsx
> +  const { authorizationStatus, children } = props;
`authorizationStatus` could be named in a more lightweight manner => `isAuth`, or `isAuthenticated`

2022-02-17 21:34 UTC, dianatsevan commented on project/src/components/private-route/private-route.tsx
> +  authorizationStatus: AuthorizationStatus;
Why `AuthorizationStatus` type?

2022-02-17 21:34 UTC, dianatsevan commented on project/src/components/error/error.tsx
> +function Error() {
Let's rename on `NotFoundPage`

2022-02-17 21:34 UTC, dianatsevan commented on project/src/const.tsx
> +export enum AppRoute {
Let's create folder `constants` where we will create specific constants' files, e.g. `src/constants/routs.ts`.

2022-02-18 04:44 UTC, olegsorokin commented on project/src/components/private-route/private-route.tsx
> +  authorizationStatus: AuthorizationStatus;
I found this realization example in a homework project:
https://github.com/htmlacademy-react/guess-melody-9/blob/6d3a170723b1e4028011899ab63c0f583b0d7473/project/src/components/private-route/private-route.tsx#L6

2022-02-18 04:45 UTC, olegsorokin commented on project/src/components/private-route/private-route.tsx
> +  authorizationStatus: AuthorizationStatus;
> Why `AuthorizationStatus` type?

I found this realization example in a homework project:
https://github.com/htmlacademy-react/guess-melody-9/blob/6d3a170723b1e4028011899ab63c0f583b0d7473/project/src/components/private-route/private-route.tsx#L6

2022-02-18 04:45 UTC, olegsorokin commented on project/src/components/private-route/private-route.tsx
> +  authorizationStatus: AuthorizationStatus;
I found this realization example in a homework project:
https://github.com/htmlacademy-react/guess-melody-9/blob/6d3a170723b1e4028011899ab63c0f583b0d7473/project/src/components/private-route/private-route.tsx#L6

2022-02-20 00:27 UTC, dianatsevan approved these changes

2022-02-20 11:50 UTC, merged